{% set name = "yamllint" %}
{% set version = "1.6.0" %}
{% set sha256 = "a095c98728c95918b8a4153c855c13e158315f8150ddad1cf9c3e831f9d7ba87" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - pyyaml

test:
  imports:
    - yamllint
  requires:
    - nose

about:
  home: https://github.com/adrienverge/yamllint
  license: GPLv3
  license_file: LICENSE
  summary: 'A linter for YAML files.'
  doc_url: https://yamllint.readthedocs.io/
  dev_url: https://github.com/adrienverge/yamllint

extra:
  recipe-maintainers:
    - proinsias
