{% set name = "yamllint" %}
{% set version = "1.23.0" %}

package:
  name: '{% set name = "yamllint" %}{{ name }}'
  version: {{ version }}

source:
  # yamllint disable-line rule:line-length
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 59f3ff77f44e7f46be6aecdb985830f73a1c51e290b7082a7d38c2ae1940f4a9

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .
  entry_points:
    - yamllint=yamllint.cli:run

requirements:
  host:
    - pip
    - python
  run:
    - pathspec >=0.5.3
    - python
    - pyyaml

test:
  source_files:
    - tests
  requires:
    - pytest
  imports:
    - yamllint
  commands:
    - python -m pytest .  # [unix]
    - yamllint --help
    - yamllint --version
    # the bot can't find the version for now
    # - cd {{ RECIPE_DIR }} && yamllint --strict --format parsable .

about:
  home: https://github.com/adrienverge/yamllint
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: A linter for YAML files.
  doc_url: https://yamllint.readthedocs.io
  doc_source_url: |
    https://github.com/adrienverge/yamllint/blob/master/docs/index.rst
  description: |
    yamllint does not only check for syntax validity, but for weirdnesses like
    key repetition and cosmetic problems such as lines length, trailing spaces,
    indentation, etc.

extra:
  recipe-maintainers:
    - proinsias
    - bollwyvl
