{% set name = "yamllint" %}
{% set version = "1.26.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b0e4c89985c7f5f8451c2eb8c67d804d10ac13a4abe031cbf49bdf3465d01087

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .
  entry_points:
    - yamllint=yamllint.cli:run

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - pathspec >=0.5.3
    - python >=3.5
    - pyyaml
    - setuptools

test:
  source_files:
    - tests
  requires:
    - pip
    - pytest
    - pytest-cov
  imports:
    - yamllint
  commands:
    - python -m pip check
    - yamllint --help
    - yamllint --version
    - pytest --cov yamllint --cov-fail-under 97 .

about:
  home: https://github.com/adrienverge/yamllint
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: A linter for YAML files.
  doc_url: https://yamllint.readthedocs.io
  doc_source_url: |
    https://github.com/adrienverge/yamllint/blob/master/docs/index.rst
  description: |
    yamllint does not only check for syntax validity, but for weirdnesses like
    key repetition and cosmetic problems such as lines length, trailing spaces,
    indentation, etc.

extra:
  recipe-maintainers:
    - proinsias
    - bollwyvl
