{% set version = "1.18.0" %}

package:
  name: '{% set name = "yamllint" %}{{ name }}'
  version: '{{ version }}'

source:
  # yamllint disable-line rule:line-length
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d42dbb35b3d28722a8c5c25de4593add0a6215b2732eb6932d89f38482c3d01c

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install --no-deps --ignore-installed ."
  entry_points:
    - yamllint=yamllint.cli:run

requirements:
  host:
    - pip
    - python
  run:
    - pathspec
    - python
    - pyyaml

test:
  source_files:
    - tests
  requires:
    - pytest
  imports:
    - yamllint
  commands:
    - python -m pytest .  # [unix]
    - yamllint --help
    - yamllint --version
    # the bot can't find the version for now
    # - cd {{ RECIPE_DIR }} && yamllint --strict --format parsable .

about:
  home: https://github.com/adrienverge/yamllint
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: 'A linter for YAML files.'
  doc_url: https://yamllint.readthedocs.io
  doc_source_url: |
    https://github.com/adrienverge/yamllint/blob/master/docs/index.rst
  description: |
    yamllint does not only check for syntax validity, but for weirdnesses like
    key repetition and cosmetic problems such as lines length, trailing spaces,
    indentation, etc.

extra:
  recipe-maintainers:
    - proinsias
    - bollwyvl
