# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: beta-xcode6.1

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=34
    - CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "T0dTmmNY7oBp0xqlqE00/FZ8YEWJ/DO0Ktmchhwn+P6wVfXQ6GqlnyC8ZtBLb40hlG+R3Nml+bX7wM5f3gGS4cQKx+j5Y46VSaaB1eTTimZndkVIOu2CI8tSw04ZsyPEn804879vXknJrNXmFgiIBjKWTS1zWGWCEeL0Vo7QI7Ai91cjOsiGt4q2mgOW9dyOX7FKLl8S5tVuQi/FLc/+EplKAyCrwIMNbE9TKTEk7bJrLwN9LpeBvgSwBQZbspgiAYgIuR7w0JCyWFXVVt7zURMZ1r6m7ZDfhpJAUCzy91tE8azrBp+yDJdzk+rx7yF16ywxKb1f1kh/8UHxzTAJnGUvCC40qyUESFi+vQl+ohGA8vxAPwXyfGzwRaHGTKrKq/xhyVXW8ODXOaiDUqyZ4C9cPKkAf9BL5jO5kEuIoO0SLfWFO6n9gqB/0R1pbH9iqWnbprxOz3cEERprvQzkZ9TPd/Y9rKEnzwteh1jjQ6quzRRAdO1s6OKSPU0eD3SkcZsk2nwa788vh1Le2S35VYGZs9xmXr2Q8mhE+FnEu1O97HHITD3wjMUkfDJ9Y6OBiDSwEIIqxlIQ0kmQZUG5cAPUQ/i3oyo0Ekjd7u7KNiJAvSJcA+Za9J/VzFeRxAErf5fFAS6oGBdFzfbrjtuK51O008SnFTrkuhCEyOZUDi8="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      source /Users/travis/miniconda3/bin/activate root
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
