# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: beta-xcode6.1

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=34
    - CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "VeILCstNs55IZ38Am7uNK1KbCgdSlOo32jUZgA9/BS1+M4IJFTAG5gmDpggsKXhmOy5WagSK1v4EasmBTdSpjQUsMOfJteJFpJ+cVvU3k7XGLmZRkE+Wk8K2V9vJDi7enwMYCvV40d0Tk+U+qg1ywzgwVHnr5tBLvHuoDaLDdNQsoh1UTOwJTaV7lv6eaKwpJq0UnY78NA8Rka9LJ6E/pPrE2XPupGUMNuVEWxzEcID5tpBv8OFc72Sj6m8uAOIUoMaCob5OeLJ3V8QiF/3mg+vpHf155tte0YmCCfYtuQa0QitnGto7xfj0dIlo7iYihJS/fXwWcynuscKwxs+2H8pOyKvGGFHZ91r/jIHCDIg7X/Oltm6k2ARLyUN00f2mUVOT3ZalRDUNjLg4wvnlsDNRSOFyoyxr3Klm2qoCrV8G+1OldkL0RRRcHTGDa2K5bvKY53ZH7vL4FqOO2tYg27LKCJViJiXBGN05tjEKzmhaWskGi6E6A329sa7PxvOtqP830f9NU3QixUnaCDR/hYrkvMwcNjpbzzldsaKyUe89CBa1IrI0whKleGda/ohZOxo4u871Nuu2q+kVt73jTh0E65luqJP184Tsb4l1NL1BH+xRbZsamu+edjXdeM+rS47haQd6BzET4KFvJX3nzqwSutiUImcF/lHCnk1dZHk="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      source /Users/travis/miniconda3/bin/activate root
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
