travis:
  secure:
    BINSTAR_TOKEN: T0dTmmNY7oBp0xqlqE00/FZ8YEWJ/DO0Ktmchhwn+P6wVfXQ6GqlnyC8ZtBLb40hlG+R3Nml+bX7wM5f3gGS4cQKx+j5Y46VSaaB1eTTimZndkVIOu2CI8tSw04ZsyPEn804879vXknJrNXmFgiIBjKWTS1zWGWCEeL0Vo7QI7Ai91cjOsiGt4q2mgOW9dyOX7FKLl8S5tVuQi/FLc/+EplKAyCrwIMNbE9TKTEk7bJrLwN9LpeBvgSwBQZbspgiAYgIuR7w0JCyWFXVVt7zURMZ1r6m7ZDfhpJAUCzy91tE8azrBp+yDJdzk+rx7yF16ywxKb1f1kh/8UHxzTAJnGUvCC40qyUESFi+vQl+ohGA8vxAPwXyfGzwRaHGTKrKq/xhyVXW8ODXOaiDUqyZ4C9cPKkAf9BL5jO5kEuIoO0SLfWFO6n9gqB/0R1pbH9iqWnbprxOz3cEERprvQzkZ9TPd/Y9rKEnzwteh1jjQ6quzRRAdO1s6OKSPU0eD3SkcZsk2nwa788vh1Le2S35VYGZs9xmXr2Q8mhE+FnEu1O97HHITD3wjMUkfDJ9Y6OBiDSwEIIqxlIQ0kmQZUG5cAPUQ/i3oyo0Ekjd7u7KNiJAvSJcA+Za9J/VzFeRxAErf5fFAS6oGBdFzfbrjtuK51O008SnFTrkuhCEyOZUDi8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
