travis:
  secure:
    BINSTAR_TOKEN: VeILCstNs55IZ38Am7uNK1KbCgdSlOo32jUZgA9/BS1+M4IJFTAG5gmDpggsKXhmOy5WagSK1v4EasmBTdSpjQUsMOfJteJFpJ+cVvU3k7XGLmZRkE+Wk8K2V9vJDi7enwMYCvV40d0Tk+U+qg1ywzgwVHnr5tBLvHuoDaLDdNQsoh1UTOwJTaV7lv6eaKwpJq0UnY78NA8Rka9LJ6E/pPrE2XPupGUMNuVEWxzEcID5tpBv8OFc72Sj6m8uAOIUoMaCob5OeLJ3V8QiF/3mg+vpHf155tte0YmCCfYtuQa0QitnGto7xfj0dIlo7iYihJS/fXwWcynuscKwxs+2H8pOyKvGGFHZ91r/jIHCDIg7X/Oltm6k2ARLyUN00f2mUVOT3ZalRDUNjLg4wvnlsDNRSOFyoyxr3Klm2qoCrV8G+1OldkL0RRRcHTGDa2K5bvKY53ZH7vL4FqOO2tYg27LKCJViJiXBGN05tjEKzmhaWskGi6E6A329sa7PxvOtqP830f9NU3QixUnaCDR/hYrkvMwcNjpbzzldsaKyUe89CBa1IrI0whKleGda/ohZOxo4u871Nuu2q+kVt73jTh0E65luqJP184Tsb4l1NL1BH+xRbZsamu+edjXdeM+rS47haQd6BzET4KFvJX3nzqwSutiUImcF/lHCnk1dZHk=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
